services:
    postal-api:
        build:
            context: './vendor/laravel/sail/runtimes/8.4'
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: 'sail-8.4/app'
        restart: unless-stopped
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
            APP_SERVICE: '${APP_SERVICE:-postal-api}'
        volumes:
            - '.:/var/www/html'
            - '../storage:/var/www/html/storage'
            - '../config/laravel.env:/var/www/html/.env'
        networks:
            - sail
        depends_on: {  }
networks:
    sail:
        driver: bridge
